### ISSUE TITLE
Browser extension: where to find actual changelog?

### ISSUE THREAD

**Issue by pictosun** [strongbox-password-safe/browser-autofill#11]
Hi,

today I found out, that the browser extension is already on version 1.2.0

But since 1.1.1 there is no changelog, or version update within Github or the different browser app stores.

Where can I find the update/changelog of those extensions and what has changed?

**Comment by strongbox-mark** [comment]
Hi @pictosun - sorry about that, I totally forgot to push changes. We don't publish a public changelog at the moment, though that's something we could consider in the future, though we usually do this on the relevant app stores rather than here in github. In terms of changes, this was mostly tech debt/refactoring, some styling change, bugfixes and the addition of en-gb localization.
